# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test, Build and Deploy to Lambda

on:
    push:
        branches: ["main"]

env:
    AWS_REGION: "eu-west-3"
    ECR_REPOSITORY: "immo_scrap"
    PYTHON_VERSION: 3.9

jobs:
    test:
        name: Testing ImmoScrap
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ env.PYTHON_VERSION }}
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ env.PYTHON_VERSION }}
            - name: Install ImmoScrap
              run: |
                  python -m pip install .
            - name: Install Test Dependencies
              run: |
                  python -m pip install -r requirements_dev.txt
            - name: Test with pytest
              run: |
                  pytest
